name: centrifuge
version: 0.4.5

description: >
  Dart client to communicate with Centrifuge and Centrifugo from DartWeb over dart:html WebSocket

author: German Saprykin <saprykin.h@gmail.com>
homepage: https://github.com/iviguera/centrifuge-dart

environment:
 sdk: '>=2.0.0  <3.0.0'

dependencies:
 meta: ^1.1.5
 protobuf: ^0.13.2

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
